apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: scpi-invest-front-tls
spec:
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: lets-encrypt
  secretName: scpi-invest-front-tls
  dnsNames:
    - {{ if .Values.ingressPrefix }}{{ .Values.ingressPrefix }}.{{ end }}scpi-invest.check-consulting.net
  usages:
  - digital signature
  - key encipherment
