apiVersion: apps/v1
kind: Deployment
metadata:
  name: scpi-invest-front
  labels:
    app: scpi-invest-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: scpi-invest-front
  template:
    metadata:
      name: scpi-invest-front
      labels:
        app: scpi-invest-front
    spec:
      nodeName: ip-10-0-3-21.ec2.internal
      containers:
        - name: scpi-invest-front
          image: mchekini/scpi-invest-front:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
      restartPolicy: Always
