apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: scpi-invest-client
  annotations:
    nginx.ingress.kubernetes.io/proxy-connect-timeout: "600"
spec:
  ingressClassName: nginx
  rules:
    - host: test.check-consulting.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: scpi-invest-inexistant
                port:
                  number: 80
