apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: scpi-invest-client
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: 'false'
spec:
  ingressClassName: nginx
  rules:
    - host: scpi-invest.check-consulting.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: scpi-invest-front
                port:
                  number: 80
