apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: scpi-invest-np
spec:
  podSelector:
    matchLabels:
      app: scpi-invest-front
  ingress:
    - ports:
        - protocol: TCP
          port: 80
  egress:
    - {}
  policyTypes:
    - Ingress
    - Egress
